version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE: "https://tech-zeyphr.onrender.com"
    ports:
      - "3000:80" # maps host:3000 to container:80
    restart: unless-stopped
